### ISSUE TITLE
Enable tooltip on click

### ISSUE THREAD

**Issue by ahmedsuffian** [marshal003/angular-help-me#1]
Lets say I have an info button and when you click on it, it displays the tooltip. How can I achieve that using this plugin?

**Comment by marshal003** [comment]
This library provides a way to segregate help texts from its HTML. Presenter of help text is completely in your hand and even you can have more than one presenter(ui-directive, used to display help text). 

Check this http://codepen.io/marshal003/pen/vKPKyk
Here, I have modified my presenter to toggle display of tooltip on clicking info tip. 

``` html
   <!-- Register My Custom Help Template -->
    <script type="text/ng-template" id="helpMe.directiveHTML">
     <!-- Toggle a flag on click -->
      <span class="glyphicon glyphicon-question-sign"
            ng-show="showHelpText" ng-click="showInfoTip=!showInfoTip">

       <!-- Use flag to show / hide tooltip -->
        <i data-ng-bind="helpText" ng-show="showInfoTip"></i>
      </span>
    </script>
```

This might not be the exact solution you are looking for, but hoping this will help you to think how to use it for your use  case.
